apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: web1-service
          servicePort: 8080
      - path: /nginx
        backend:
          serviceName: web2-service
          servicePort: 8080
