apiVersion: v1
kind: Deployment
metadata:
  name: web1-deployment
  namespace: default
  labels:
    name: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx1
  template:
    metadata:
      labels:
        name: nginx1
  containers:  
  - name: node
    image: nginx   
    ports:
    - containerPort: 80