apiVersion: v1
kind: Service
metadata:
  name: web1-stateful-service 
  labels:
    app: nginx
spec:
  selector:
    name: web1-statefulset
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP 
  type: NodePort
