apiVersion: v1 
kind: Service
metadata:
  name: web1-service
  namespace: hostpath 
spec:
  selector:
    name: web1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
