apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web1-pod-statefulset
spec:
  selector:
    matchLabels:
      name: web1-statefulset # has to match .spec.template.metadata.labels
  serviceName: "nginx-statefulset"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
       name: web1-statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-statefulset
        image: nginx
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
          name: web1-port
        volumeMounts:
        - name: www-vol
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: www-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd1"
      resources:
        requests:
          storage: 4Gi
